include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false # skip if you don't want doc comments enforced on every public member
    one_member_abstract: false # skip warning for one member abstracts
